### PR TITLE
Fix/uh_convolution

### PR DESCRIPTION
**Pull request by jhamman**
cc @orianac, @yixinmao, and @bartnijssen 

Just look at this commit: f80f9eb

### CODE REVIEW

**Comment by jhamman** [comment]
## There seems to be a bug in the Lohmann (Fortran routing model)

The [bug](https://github.com/jhamman/VIC_Routing/blob/Fortran_version/src/unit_hyd_routines.f#L120-L126) is thought to be in the convolution of the river routing unit hydrographs (UHs). In the code below, `FR(:, 1)` is the unit hydrograph representing the net river routing UH for the current grid cell (`I, J`), `FR(:, 2)` is the net UH for the current grid cell plus the convolution of the UH for the next downstream grid cell. `UHM(I,J,L)` is the river routing UH for the current grid cell only. `TMAX` and `LE` are the sizes of the time dimension of `FR` and `UHM` respectively.

#### The bug

The convolution is skipping the diagonal (e.g. when `T=L`) members of each array. There is no reason not to do the convolution for `T=1,l=1`. This (as I will show in detail below) leads to a "lagged" final UH.

```
...
DO T = 1, TMAX
  DO L = 1, LE
     IF ((T-L) .GT. 0) THEN
       FR(T,2) = FR(T,2) + FR(T-L,1)*UHM(I,J,L) 
     END IF
   END DO
END DO
```

## As they say, the proof is in the pudding

Here are the three 1-D convolution schemes used in either RVIC or the Lohmann Fortran version
1.  RVIC (see [`convolve_np`](http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.convolve.html))
2.  Lohmann - Fortran - Original (`convolve_orig`) --> This implementation has the diagonal bug described above.
3.  Lohmann - Fortran - Fixed (`convolve_fixed`)

*Note that the two functions below are adjusted for 0 vs. 1 indexing in Python vs. C respectively.

``` python
# RVIC
import numpy as np
from numpy import convolve as convolve_np

```

``` python
# Lohmann - Fortran - Original
def convolve_orig(a, v):
    out = np.zeros(len(a) + len(v) - 1)
    for t in range(0, len(a)):
        for l in range(0, len(v)):
            if ((t-l) > 0):
                out[t] += a[t-l] * v[l]

    return out
```

``` python
# Lohmann - Fortran - Fixed
def convolve_fixed(a, v):
    out = np.zeros(len(a) + len(v) - 1)
    for t in range(0, len(a)):
        for l in range(0, len(v)):
            if ((t-l) >= 0):
                out[t] += a[t-l] * v[l]

    return out
```

``` python
# Two 1d arrays
a = [1, 2, 3, 0, 0]
b = [0, 1, 0.5]
```

``` python
# Numpy's convolution
convolve_np(a, b)
```

```
array([ 0. ,  1. ,  2.5,  4. ,  1.5,  0. ,  0. ])
```

``` python
# The orignal Lohmann model convolution
convolve_orig(a, b)
```

```
array([ 0. ,  0. ,  2. ,  4. ,  1.5,  0. ,  0. ])
```

``` python
# The "fixed" Lohmann model convolution
convolve_fixed(a, b)
```

```
array([ 0. ,  1. ,  2.5,  4. ,  1.5,  0. ,  0. ])
```

``` python

```

**Comment by bartnijssen** [comment]
@jhamman : Note that this is a *non-trivial* bug fix as it will actually change the answer in the routed results. I wonder whether we need to make this apparent in the version number.

**Comment by jhamman** [comment]
@bartnijssen - I think tagging the current version would make sense (1.0 probably). Then merging and making a second tag (1.1) would suffice.  Beyond that, an email to the `vic_users` list should explain the change in detail.

**Comment by bartnijssen** [comment]
@jhamman : Please proceed as you suggest and go ahead and merge (after tagging)

**Comment by jhamman** [comment]
@bartnijssen - just merged / tagged.  I'll send an email to the VIC users list pointing to this conversation after the holidays.

**Pull request merged**
